steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set project mystical-runway-364716 && gcloud       config set app/cloud_build_timeout 1600 && gcloud app deploy --project=mystical-runway-364716
']
  env:
    - 'CAPTCHA_PUBLIC_KEY=$_CAPTCHA_PUBLIC_KEY'
    - 'CAPTCHA_PRIVATE_KEY=$_CAPTCHA_PRIVATE_KEY'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud datastore indexes create index.yaml']
  timeout: '1600s'